let users = [{ "id": 1, "first_name": "Sarah", "email": "sgrainge0@xinhuanet.com", "gender": "Female" },
{ "id": 2, "first_name": "Gwenni", "email": "gmonard1@tripod.com", "gender": "Female" },
{ "id": 3, "first_name": "Evvie", "email": "ebyne2@rakuten.co.jp", "gender": "Female" },
{ "id": 4, "first_name": "Kellie", "email": "kporson3@comcast.net", "gender": "Female" },
{ "id": 5, "first_name": "Nolan", "email": "nfalla4@yandex.ru", "gender": "Male" },
{ "id": 6, "first_name": "Weylin", "email": "wsorrel5@ning.com", "gender": "Male" },
{ "id": 7, "first_name": "Georgie", "email": "gwalford6@ebay.com", "gender": "Polygender" },
{ "id": 8, "first_name": "Kurt", "email": "kmackintosh7@multiply.com", "gender": "Male" },
{ "id": 9, "first_name": "Cilka", "email": "cembleton8@unblog.fr", "gender": "Female" },
{ "id": 10, "first_name": "Hunt", "email": "hsworne9@123-reg.co.uk", "gender": "Male" },
{ "id": 11, "first_name": "Lexy", "email": "lstedmana@loc.gov", "gender": "Female" },
{ "id": 12, "first_name": "Ly", "email": "lbrameltb@macromedia.com", "gender": "Male" },
{ "id": 13, "first_name": "Roshelle", "email": "rroycec@yolasite.com", "gender": "Genderqueer" },
{ "id": 14, "first_name": "Skip", "email": "smacvicard@devhub.com", "gender": "Male" },
{ "id": 15, "first_name": "Michel", "email": "mhartope@springer.com", "gender": "Male" },
{ "id": 16, "first_name": "Marcille", "email": "mdaycef@nytimes.com", "gender": "Female" },
{ "id": 17, "first_name": "Latrina", "email": "lreastg@live.com", "gender": "Female" },
{ "id": 18, "first_name": "Rosabella", "email": "rblaszczynskih@cnbc.com", "gender": "Female" },
{ "id": 19, "first_name": "Violette", "email": "vpauluzzii@geocities.com", "gender": "Female" },
{ "id": 20, "first_name": "Bobbye", "email": "bfoatj@fda.gov", "gender": "Female" },
{ "id": 21, "first_name": "Eada", "email": "etapendenk@bloomberg.com", "gender": "Female" },
{ "id": 22, "first_name": "Leonora", "email": "lcaponl@amazon.de", "gender": "Female" },
{ "id": 23, "first_name": "Beatrix", "email": "bnelmesm@umich.edu", "gender": "Female" },
{ "id": 24, "first_name": "Inga", "email": "iswyern@ameblo.jp", "gender": "Female" },
{ "id": 25, "first_name": "Demetra", "email": "dkinlocho@wordpress.com", "gender": "Female" },
{ "id": 26, "first_name": "Teodora", "email": "tbeeseyp@theatlantic.com", "gender": "Female" },
{ "id": 27, "first_name": "Venus", "email": "vkinnaneq@ucoz.com", "gender": "Female" },
{ "id": 28, "first_name": "Marcelo", "email": "magarr@deliciousdays.com", "gender": "Male" },
{ "id": 29, "first_name": "Yevette", "email": "ypriests@hugedomains.com", "gender": "Female" },
{ "id": 30, "first_name": "Terrel", "email": "thebert@ebay.com", "gender": "Male" },
{ "id": 31, "first_name": "Blancha", "email": "bwalsheu@huffingtonpost.com", "gender": "Genderfluid" },
{ "id": 32, "first_name": "Dolph", "email": "dcoetzeev@oakley.com", "gender": "Male" },
{ "id": 33, "first_name": "Eden", "email": "escirmanw@nsw.gov.au", "gender": "Female" },
{ "id": 34, "first_name": "Datha", "email": "dcroydonx@theatlantic.com", "gender": "Female" },
{ "id": 35, "first_name": "Orin", "email": "otremeery@alibaba.com", "gender": "Male" },
{ "id": 36, "first_name": "Moses", "email": "msterryz@symantec.com", "gender": "Male" },
{ "id": 37, "first_name": "Mildrid", "email": "mwallege10@usa.gov", "gender": "Female" },
{ "id": 38, "first_name": "Nadine", "email": "ndufaire11@123-reg.co.uk", "gender": "Female" },
{ "id": 39, "first_name": "Merilyn", "email": "mmcturlough12@w3.org", "gender": "Female" },
{ "id": 40, "first_name": "Skylar", "email": "sfitton13@miibeian.gov.cn", "gender": "Male" },
{ "id": 41, "first_name": "Molly", "email": "mdesavery14@amazon.co.jp", "gender": "Female" },
{ "id": 42, "first_name": "Monro", "email": "mwestern15@51.la", "gender": "Male" },
{ "id": 43, "first_name": "Daniel", "email": "dsinnock16@dion.ne.jp", "gender": "Male" },
{ "id": 44, "first_name": "Pietrek", "email": "pgadesby17@goodreads.com", "gender": "Male" },
{ "id": 45, "first_name": "Devin", "email": "ddeering18@ft.com", "gender": "Male" },
{ "id": 46, "first_name": "Carmella", "email": "chuby19@behance.net", "gender": "Female" },
{ "id": 47, "first_name": "Janelle", "email": "jshapera1a@angelfire.com", "gender": "Female" },
{ "id": 48, "first_name": "Barr", "email": "bhackleton1b@elpais.com", "gender": "Male" },
{ "id": 49, "first_name": "Gabie", "email": "gmcmeekan1c@aboutads.info", "gender": "Female" },
{ "id": 50, "first_name": "Starr", "email": "sfochs1d@myspace.com", "gender": "Female" }]

for (user of users) {
    console.log(user.email)
}